### ISSUE TITLE
Dual extruder print area.

### ISSUE THREAD

**Issue by Artimidorus** [tracedgod/FlashForge-Dreamer-Cura-Definitions#2]
First of all. Thanks for your effort making this profile and sharing it.
   I'm new to 3d printing and am enjoying the learning how to print in 3 dimensions. I was using the flashforge firmware but encountered difficulty trying to make the extruder change temp mid print. So I changed firmware to marlin after some research. Now to my problem.
    I understand with the dual extruder setup you loose the offset amount in cura. Is there a way to overcome that? The hardware is capable of using the whole build plate with either extruder. How can I make the software recognize that?
Thanks for your time.

**Comment by Artimidorus** [comment]
I fixed my issue by adding 
"nozzle_offsetting_for_disallowed_areas": false
just after 
"machine_extruder_trains": {            
            "0": "flashforge_dreamer_extruder_0",
            "1": "flashforge_dreamer_extruder_1"
 }
in the file flashforge_dreamer.def.json

now im working on getting the offset set for my printer

**Comment by tracedgod** [comment]
> I fixed my issue by adding "nozzle_offsetting_for_disallowed_areas": false just after "machine_extruder_trains": { "0": "flashforge_dreamer_extruder_0", "1": "flashforge_dreamer_extruder_1" } in the file flashforge_dreamer.def.json
> 
> now im working on getting the offset set for my printer

Hey there, thanks for the info on getting the nozzle offset! I noticed this as well, just didn't really have time to look into it much. Did you ever get the offset right calibrated?

**Comment by Artimidorus** [comment]
One nozzle is perfect. The other I haven't attempted yet. That will be next weekends project.

**Comment by Artimidorus** [comment]
So i noticed the offset works perfectly without further changes if i print from an SD card instead of the USB cable.
